apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore-project
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookstore-project
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bookstore-project
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bookstore-project
spec:
  replicas: 1
