apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore-project
spec:
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          env:
            - name: NODE_ENV
              value: "development"
            - name: LOG_LEVEL
              value: "debug"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookstore-project
spec:
  template:
    spec:
      containers:
        - name: frontend
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "100m"
