apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore-project
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookstore-project
spec:
  replicas: 3
