apiVersion: v1
kind: ResourceQuota
metadata:
  name: bookstore-quota
  namespace: bookstore-project
  labels:
    app: bookstore
spec:
  hard:
    # Compute Resources
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"

    # Storage
    requests.storage: "10Gi"
    persistentvolumeclaims: "5"

    # Object Counts
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
    replicationcontrollers: "5"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: bookstore-limits
  namespace: bookstore-project
  labels:
    app: bookstore
spec:
  limits:
    # Container limits
    - type: Container
      max:
        cpu: "2"
        memory: "2Gi"
      min:
        cpu: "10m"
        memory: "16Mi"
      default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"

    # Pod limits
    - type: Pod
      max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "10m"
        memory: "16Mi"

    # PVC limits
    - type: PersistentVolumeClaim
      max:
        storage: "5Gi"
      min:
        storage: "100Mi"
